#! /usr/bin/env python

import os
import sys
import time
import serial

def serial_write(data):
    for char in data:
        port.write(char)
        port.flush()

def serial_read():
    try:
        return port.read()
    except:
        print 'Error connecting to device'
        sys.exit(1)

try:
  port = serial.Serial('/dev/tty.usbserial', baudrate=9600)
except serial.SerialException:
  print 'Could not connect to serial port /dev/tty.usbserial'
  print 'Please confirm you device is plugged in and powered on, and the driver is installed'
  sys.exit(1)

if len(sys.argv) < 2:
    print 'Please specify a file to compile and run'
    sys.exit(1)

try:
    program = open(sys.argv[1], 'r').read()
except:
    print 'Could not open file %s' % sys.argv[1]
    sys.exit(1)
program = program.replace('\n', '')
program = program.replace('\r', '')

print 'Waiting for MINMON'

while True:
    time.sleep(0.2)
    serial_write('D')
    data = serial_read()
    if data == '>':
        break

print 'Downloading Code...'

#serial_write(program)

print 'Done!!'

port.close()
